### ISSUE TITLE
client_allowed_sans is not working

### ISSUE THREAD

**Issue by duj4** [prometheus/exporter-toolkit#153]
client_allowed_sans is an import function to us since previous web-config cannot verify the client/server host via hostname in mTLS authentication.
I just tried to enable this flag but from both alertmanager and prometheus server, it complains:
msg="Unable to parse configuration" err="yaml: unmarshal errors:\n line 8: field client_allowed_sans not found in type web.TLSStruct".

Prometheus version is 2.37.6
Alertmanager version is 0.25.0

It seems this is not merged into Prometheus code yet, isn't it? If this is the case, is there any ETA for this one?

Thanks.

**Comment by SuperQ** [comment]
No, this is not supported in the LTS release, as that release track is bugfixes only, no new features.

Please upgrade to the latest release, v2.44.0.

**Comment by duj4** [comment]
@SuperQ , I have checked the https://prometheus.io/docs/prometheus/latest/configuration/https/, it does not mention "client_allowed_sans" is supported. I downloaded the latest version 2.44.0 and tried to bring it up with --web.config.file, in which I added client_allowed_sans, still the same error.
