### ISSUE TITLE
Tests fail with go 1.21

### ISSUE THREAD

**Issue by NightTsarina** [prometheus/exporter-toolkit#171]
Found in: a7dd218 (tag: v0.10.0)

Hi,

The exporter toolkit stopped building cleanly in Debian a few days ago. After some investigation, I found that in go 1.21 the  crypto/tls package [changed some of the error messages](https://github.com/golang/go/commit/62a994837a57a7d0c58bb364b580a389488446c9), making the tests fail as the regexes do not match any more.

The patch below solves the issue:

```diff
--- a/web/tls_config_test.go
+++ b/web/tls_config_test.go
@@ -64,10 +64,11 @@
 		"No HTTP2 cipher":              regexp.MustCompile(`TLSConfig.CipherSuites is missing an HTTP/2-required`),
 		// The first token is returned by Go <= 1.17 and the second token is returned by Go >= 1.18.
 		"Incompatible TLS version": regexp.MustCompile(`protocol version not supported|no supported versions satisfy MinVersion and MaxVersion`),
-		"Bad certificate":          regexp.MustCompile(`bad certificate`),
 		"Invalid value":            regexp.MustCompile(`invalid value for`),
 		"Invalid header":           regexp.MustCompile(`HTTP header ".*" can not be configured`),
 		"Invalid client cert":      regexp.MustCompile(`bad certificate`),
+		"Missing client cert":      regexp.MustCompile(`certificate required`),
+		"Unknown CA":               regexp.MustCompile(`unknown certificate authority`),
 	}
 )
 
@@ -300,7 +301,7 @@
 			Name:           `valid tls config yml and tls client with RequireAnyClientCert`,
 			YAMLConfigPath: "testdata/tls_config_noAuth.requireanyclientcert.good.yml",
 			UseTLSClient:   true,
-			ExpectedError:  ErrorMap["Bad certificate"],
+			ExpectedError:  ErrorMap["Missing client cert"],
 		},
 		{
 			Name:           `valid headers config`,
@@ -332,7 +333,7 @@
 			Name:           `valid tls config yml and tls client with RequireAndVerifyClientCert`,
 			YAMLConfigPath: "testdata/tls_config_noAuth.requireandverifyclientcert.good.yml",
 			UseTLSClient:   true,
-			ExpectedError:  ErrorMap["Bad certificate"],
+			ExpectedError:  ErrorMap["Missing client cert"],
 		},
 		{
 			Name:              `valid tls config yml and tls client with RequireAndVerifyClientCert (present certificate)`,
@@ -346,7 +347,7 @@
 			YAMLConfigPath:    "testdata/tls_config_noAuth.requireandverifyclientcert.good.yml",
 			UseTLSClient:      true,
 			ClientCertificate: "client2_selfsigned",
-			ExpectedError:     ErrorMap["Bad certificate"],
+			ExpectedError:     ErrorMap["Unknown CA"],
 		},
 		{
 			Name:              `valid tls config yml and tls client with VerifyPeerCertificate (present good SAN DNS entry)`,
```

**Comment by SuperQ** [comment]
Boo, slightly annoying since it now depends on the compiler version. I guess we have to bump the `go` requirement directly to 1.21.

**Comment by NightTsarina** [comment]
Yeah, I realised the same after submitting the patch yesterday. Another option could be to change the regexes to match both versions of the errors.

On 27 September 2023 6:51:47 a.m. IST, Ben Kochie ***@***.***> wrote:
>Boo, slightly annoying since it now depends on the compiler version. I guess we have to bump the `go` requirement directly to 1.21.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/exporter-toolkit/issues/171#issuecomment-1736744437
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Martina Ferrari (Tina/mobile)

**Comment by dswarbrick** [comment]
I suspect that at least some of the tests could be refactored to use error types or sentinel errors from the x509 package, and check them with `errors.As(err, &x509.FooError{})`, perhaps with a less strict regex once the error type has been narrowed down.
