### ISSUE TITLE
kingpin is in CONTRIBUTIONS ONLY state

### ISSUE THREAD

**Issue by LStuker** [prometheus/exporter-toolkit#173]
The [kingpin](https://github.com/alecthomas/kingpin) command line parser library isn't actively maintained by the origin author any more. The author has put the project into [CONTRIBUTIONS ONLY](https://github.com/prometheus/exporter-toolkit/issues/new#contributions-only) state.

What are the plans for the exporter-toolkit or the Prometheus project in general? _(Kingpin is widely used in many Prometheus projects.)_ 
Are their planes to be migrated to a different cli library?

**Comment by SuperQ** [comment]
The kingpin library has been contributions only for many years. But is feature complete and stable enough that we haven't seen a need to migrate away. There have even been some recent contributions that have been some nice improvements.

The library is not deprecated or archived. I don't think there's enough of an issue here to migrate the entire Prometheus ecosystem away from it.

**Comment by LStuker** [comment]
Thanks for the quick feedback! I think we can close the issue here and move the discussion if required to [prometheus-dev community](https://prometheus.io/community/).
