### ISSUE TITLE
Provide option to start webserver using slog

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/exporter-toolkit#239]
[Slog](https://pkg.go.dev/golang.org/x/exp/slog) was added to the Go standard libraries as an alternative for structured logging. A lot of tools are trying to migrate to slog, aiming to remove their dependency tree in third-party libraries like `go-kit`

A few examples:
* https://github.com/prometheus/prometheus/issues/14355
* https://github.com/prometheus/node_exporter/pull/3097
* https://github.com/prometheus-operator/prometheus-operator/issues/6183

exporter-toolkit still requires go-kit in its contructor:
https://github.com/prometheus/exporter-toolkit/blob/61beb2cb9c212dc4423a13aa5d1abdaf047e87f1/web/tls_config.go#L30
https://github.com/prometheus/exporter-toolkit/blob/61beb2cb9c212dc4423a13aa5d1abdaf047e87f1/web/tls_config.go#L287

Would it make sense to provide another one with slog?

**Comment by SuperQ** [comment]
The other proposal I had was that we make a breaking change here that we just convert this over to slog and drop go-kit.

Depends on how much work it is to support a second option.

**Comment by SuperQ** [comment]
We decided to go with the breaking change. This is now released.
