### ISSUE TITLE
feature: Exporter homepage package

### ISSUE THREAD

**Issue by SuperQ** [prometheus/exporter-toolkit#3]
One of the boilerplate items that exporters have is the `/` path status page. Most currently have a simple description and a link to the the `/metrics` path.

I don't want to go crazy and have a react UI, but some expanded information would be useful.

Some things to include:
* Version / build info.
* Flags.
* Additional documentation links
* A link to the source homepage
* Some minimal CSS to make it pretty

The package should auto-discover as much as possible, but include a New method with some struct fields to assist in customizations.

**Comment by brian-brazil** [comment]
The version/build info stuff depends on our build system.

**Comment by SuperQ** [comment]
Yes, exactly, that's one of the easier ones to handle automatically since we can include `github.com/prometheus/common/version` in the helper package and do something as simple as include `version.Print()` in the homepage output, or maybe add a new `version.PrintHTML()` function to the version package.

**Comment by roidelapluie** [comment]
I am happy to make our build system more public ; I have used it yesterday on https://github.com/inuits/mqttgateway and it is really a nice piece of engineering.

**Comment by roidelapluie** [comment]
cc @simonpasquier WDYT how do you feel about promoting the promu and circleci orb to the large community?

**Comment by brian-brazil** [comment]
> Yes, exactly, that's one of the easier ones to handle automatically since we can include

My point was that it's not that simple, as that package is tightly bound to our build system. If you do a normal Go build all you'll get is the version of Go that was used.

**Comment by SuperQ** [comment]
@brian-brazil That's not an argument against making it possible to work. Many exporters use the common version package, with whatever build system they use, to embed whatever sub-components of the version strings they want.

For example, GitLab [uses go build, but has a Prometheus Version helper](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/lib/gitlab/prometheus_helper.rb) to inject the desired versioning into the build.

**Comment by brian-brazil** [comment]
I never said it was, however unlike the other items in the list it's not soley a matter of Go coding.

**Comment by SuperQ** [comment]
It pretty much is just a bit of Go code. The same way exporters use `version.Print()` to do whatever they want, we can use it to format an HTML version.

Our build system is optional. For example, I've used it with a [simple Makefile injection](https://github.com/noisebridge/rfid-access-control/blob/master/software/earl/Makefile).

**Comment by SuperQ** [comment]
The first version of this was completed in #51
