### ISSUE TITLE
Speed up bcrypt / basic auth

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/exporter-toolkit#31]
Bcrypt / Basic auth adds a certain overhead to the http connections.

We should somehow cache successful valid logins to speed them up.

See https://github.com/caddyserver/caddy/issues/3462 and https://github.com/caddyserver/caddy/commit/9a7756c6e4b4ddb945bede3ddb2dfbf241208915

**Comment by SuperQ** [comment]
I think this is done in https://github.com/prometheus/exporter-toolkit/pull/32 (plus the other related fixes)

**Comment by roidelapluie** [comment]
Yes :)
