### ISSUE TITLE
how to configure cipher_suites?

### ISSUE THREAD

**Issue by duculete** [prometheus/exporter-toolkit#52]
```
cipher_suites:
    - TLS_RSA_WITH_AES_128_CBC_SHA256
    - TLS_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384
```

vel=error ts=2021-05-18T07:56:16.290Z caller=node_exporter.go:198 err="unknown cipher: TLS_RSA_WITH_AES_128_CBC_SHA256"

**Comment by roidelapluie** [comment]
TLS_RSA_WITH_AES_128_CBC_SHA256 is considered insecure by golang therefore can not be used with the exporter toolkit.

The reason is that  CBC-SHA256 suites have no Lucky13 countermeasures.
